[[news]]
date = "2025-12"
content = "I officially get my PhD degree after the graduation ceremony! ðŸŽ“"

[[news]]
date = "2025-11"
content = "One paper about unauthorized image editing prevention is accepted by IEEE Transactions on Information Forensics and Security"

[[news]]
date = "2025-11"
content = "One paper about facial privacy protection is accepted by Pattern Recognition"

[[news]]
date = "2025-11"
content = "One paper about medical LLM is accepted by IEEE Transactions on Affective Computing"

[[news]]
date = "2025-10"
content = "I start to serve as the leading guest editor for a special issue of Pattern Recognition"

[[news]]
date = "2025-07"
content = "One paper about digital intellectual property protection is accepted by Pattern Recognition"

[[news]]
date = "2025-06"
content = "I passed my PhD viva with only typo corrections ðŸŽ‰"

[[news]]
date = "2025-04"
content = "I submitted my PhD thesis"

[[news]]
date = "2025-04"
content = "One paper about federated learning security is accepted by IEEE Transactions on Neural Networks and Learning Systems"

[[news]]
date = "2025-04"
content = "One CVPR paper is selected as highlight paper"

[[news]]
date = "2025-03"
content = "One paper about LLM backdoor attack is accepted by Information Fusion"

[[news]]
date = "2025-02"
content = "Two papers are accepted by CVPR 2025"

[[news]]
date = "2025-02"
content = "One paper about LLM backdoor attack is accepted by Transactions on Machine Learning Research"